stages:
  split_data:
    cmd: python src/data/split.py
    deps:
      - src/data/split.py
      - data/raw_data/raw.csv
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize_data:
    cmd: python src/data/normalize.py
    deps:
      - src/data/normalize.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv
      - models/scaler.pkl

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - src/models/grid_search.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    outs:
      - models/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/best_params.pkl
    outs:
      - models/trained_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/trained_model.pkl
    metrics:
      - metrics/scores.json:
          cache: false
    outs:
      - data/processed_data/y_pred.csv
